// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM1agmgc1v7nSy0GQwsqP_oXHoG1w57WA', // Update with the correct API key
    appId: '1:664518848434:android:bdc33c8f6f6d36d709beab', // Update with your app ID
    messagingSenderId: '664518848434', // Update with your sender ID
    projectId: 'xtranger-1mc', // Update with your project ID
    storageBucket: 'xtranger-1mc.appspot.com', // Update with your storage bucket
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_v0H1li8O5lUojHJRiACNabxCJJ96edg', // Update with your API key
    appId: '1:664518848434:ios:16f061bd4c7b8a2409beab', // Update with your iOS app ID
    messagingSenderId: '664518848434', // Use the sender ID from your Firebase project
    projectId: 'xtranger-1mc', // Update with your project ID
    storageBucket: 'xtranger-1mc.appspot.com', // Update with your storage bucket
    iosClientId: '664518848434-p9d0kss2gfjbli1ffhmfpbip0tpm8u84.apps.googleusercontent.com', // From plist
    iosBundleId: 'com.onemorecode.selectable', // Bundle ID from plist
  );
}
